@startuml

title "Zarządzanie kontem"
' skinparam nodesep 100
' skinparam linetype polyline
left to right direction
package Użytkownicy {
 actor "Niezalogowany Użytkownik" as uu
 actor "Użytkownik" as u
 actor "Administrator" as admin
 admin -|> u
 u -|> uu
}

Użytkownicy --[hidden]r--> Aplikacja

' actor "Firebase" as fb
' Aplikacja --[hidden]l--> fb
package Aplikacja {
 together {
  together {
   usecase "Logowanie przez konto google" as u1
   ' usecase "Rejestracja przez konto google" as u2
  }
  usecase "Ocenianie ścieżek" as u3
  usecase "Tworzenie ścieżek" as u4
  usecase "Przeglądanie ścieżek" as u5
  usecase "Zarządzanie lokalnymi ścieżkami" as u8
 }
 usecase "Komentowanie/ocenianie ścieżek" as u7
 usecase "Zarządzanie ścieżkami konta" as u6
 usecase "Usuwanie/Moderowanie ścieżek" as u10
 together {
  usecase "edycja trasy" as u12
  usecase "poprzez stawianie znaczników" as u13
  usecase "poprzez nagrywanie lokalizacji" as u14
 }

 ' usecase "filtrowanie i sortowanie ścieżek" as u9
 usecase "edycja punktów stopu" as u15
 usecase "edycja opisu" as u16
 usecase "ustawianie prywatności ścieżki" as u17
 usecase "usuwanie/edycja" as u18
}
' layout
' u <|-- admin
' uu <|-- u

' u --u-|>uu
' admin--u-|>u

uu --> u1
' uu --> u2
uu --> u4
uu --> u5
uu --> u8


u --> u3
u --> u6
u --> u7

admin --> u10

u13 -|> u12
u14 -|> u12

u15 .u.>  u4 : <<extend>>
u16 .u.>  u4 : <<extend>>
u12 .u.> u4 : <<extend>>

' u9 .u.> u5 : <<extend>>

u17 .u.> u6 : <<extend>>
u18 .u.> u6 : <<extend>>

u18 .u.> u8 : <<extend>>

' fb -u-> u5
' fb -u-> u6
' fb -u-> u7
' fb -u-> u1
' fb -u-> u2


' u --> UC1
' u --> UC2
' u --> UC3
' u --> UC4
' UC4 <.. UC5 : <<extend>>
' UC2 <.. UC6 : <<extend>>
@enduml
