@startuml
!theme _none_
left to right direction
actor "Użytkownik" as fc
rectangle "Tworzenie mapy" {
 usecase "Tworzenie trasy" as UC1
 usecase "Dodawanie Punktów Stopu" as UC2
 usecase "Tworzenie trasy poprzez nagrywanie lokalizacji" as UC3
 usecase "Tworzenie trasy poprzez wskazanie jej na mapie" as UC4

}
fc --> UC1
fc --> UC2
fc --> UC3
fc --> UC4
@enduml